name: run lunch.py

on:
  schedule:
    - cron: '*/15 0 * * *'
    # - cron: '0 1 * * 1-5'
    # - cron: '30 1 * * 1-5' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run lunch.py
        env:
          git_token: ${{ secrets.git_token }}
          hampr_email: ${{ secrets.hampr_email }}
          hampr_password: ${{ secrets.hampr_password }}
        run: python lunch.py